version: "3.9"

services:
  app:
    build:
      context: .
      target: prod
    container_name: acquisitions-app
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    restart: unless-stopped

# Note: In production we do NOT run Neon Local. The app connects to the managed Neon
# Cloud database using the DATABASE_URL provided in .env.production (or external secrets).